--обновление (+ закр)
update
F_SPU_STAJ_AGGR trg
set
trg.YY_STAJ=src.YY_STAJ,
trg.MM_STAJ=src.MM_STAJ,
trg.DD_STAJ=src.DD_STAJ,
--START_DATE
trg.END_DATE=src.END_DATE,
trg.UPDATE_DATE=src.UPDATE_DATE
from
#PS_NZ_STG011.DATABASE#.#PS_NZ_STG011.USERNAME#.F_SPU_STAJ_AGGR_p1 src
where 
src.INDIVIDUAL_ACCOUNT_GID=trg.INDIVIDUAL_ACCOUNT_GID
and FLG_INS=0;
--вставка
INSERT INTO F_SPU_STAJ_AGGR 
(
INDIVIDUAL_ACCOUNT_GID,
YY_STAJ,
MM_STAJ,
DD_STAJ,
START_DATE,
END_DATE,
UPDATE_DATE
)
select
INDIVIDUAL_ACCOUNT_GID,
YY_STAJ,
MM_STAJ,
DD_STAJ,
START_DATE,
END_DATE,
UPDATE_DATE
from 
#PS_NZ_STG011.DATABASE#.#PS_NZ_STG011.USERNAME#.F_SPU_STAJ_AGGR_p1 src
where FLG_INS=1;